[build.env]
passthrough = [
  "RUST_BACKTRACE",
  "RUST_LOG",
  "MMAL_LIB_DIR",
  "MMAL_INCLUDE_DIR",
  "VL53L1X_CC", 
  "VL53L1X_AR"
]

# Raspberry Pi 3
[target.armv7-unknown-linux-gnueabihf]
image = "pedrosland/armv7-unknown-linux-gnueabihf:latest"
