#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

# Define the target host, private key path, and the paths of the files
readonly TARGET_HOST=berry@RE1
readonly PRIVATE_KEY_PATH=~/.ssh/id_rsa
readonly SCRIPT_FOLDER=./python_tester/
readonly MAIN_FILE_PATH=./python_tester/test_server.py

readonly REMOTE_PATH=/home/berry/

# Copy the files to the remote machine
scp -r -i ${PRIVATE_KEY_PATH} ${SCRIPT_FOLDER} ${TARGET_HOST}:${REMOTE_PATH}

# Run the file1 with Python on the remote machine
ssh -i ${PRIVATE_KEY_PATH} -t ${TARGET_HOST} "cd ${REMOTE_PATH}/${SCRIPT_FOLDER}; sudo python3 ${REMOTE_PATH}/${MAIN_FILE_PATH}"


