#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

# Define the target host, private key path, and the paths of the files
readonly TARGET_HOST=berry@RE1
readonly PRIVATE_KEY_PATH=~/.ssh/id_rsa
readonly CAMERA_SCRIPT_FOLDER_PATH=./sensor_test
readonly CAMERA_MAIN_PATH=./sensor_test/sensor_test.py

readonly REMOTE_PATH=/home/berry/

# Copy the files to the remote machine
scp -r -i ${PRIVATE_KEY_PATH} ${CAMERA_SCRIPT_FOLDER_PATH} ${TARGET_HOST}:${REMOTE_PATH}

# Run the file1 with Python on the remote machine
ssh -i ${PRIVATE_KEY_PATH} -t ${TARGET_HOST} "sudo python3 ${REMOTE_PATH}/${CAMERA_MAIN_PATH}"


